#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT CONNECT ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  
  \connect $APP_DB_NAME $POSTGRES_USER
  BEGIN;
    CREATE SCHEMA $APP_DB_SCHEMA;
    GRANT USAGE ON SCHEMA $APP_DB_SCHEMA TO $APP_DB_USER;

    CREATE TABLE IF NOT EXISTS $APP_DB_SCHEMA.expenses (
	    id SERIAL PRIMARY KEY NOT NULL,
	    amount FLOAT NOT NULL,
      created TIMESTAMP NOT NULL
    );

    GRANT SELECT , INSERT , UPDATE , DELETE ON TABLE $APP_DB_SCHEMA.expenses TO $APP_DB_USER;
    GRANT USAGE , SELECT ON SEQUENCE $APP_DB_SCHEMA.expenses_id_seq to $APP_DB_USER;
  COMMIT;
EOSQL